[package]

name = "rust-model"
version = "0.0.1"
authors = ["Luke Metz <luke.metz@students.olin.edu>"]

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra.git"

[dependencies.stl]
path="../rust-stl"

